{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-dada2
  version: {{ version }}

source:
  path: ../..

build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - biom-format >=2.1.5,<2.2.0
    - bioconductor-dada2 1.2
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_dada2
    - qiime2.plugins.dada2

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
